### ISSUE TITLE
Update location_nearby-organizations.sparql to avoid memory allocatoin issues

### ISSUE THREAD

**Issue by Daniel-Mietchen** [ad-freiburg/scholia#72]
This relates to 
- https://github.com/ad-freiburg/scholia/issues/63 
and a discussion with @hannahbast .

https://qlever.scholia.wiki/location/Q791#nearby-organizations
<img width="1345" height="543" alt="Image" src="https://github.com/user-attachments/assets/82d3d0ce-83b1-4a5b-ab2d-d09d4ba474b3" />

vs.
https://qlever.dev/wikidata/J4PwWD

<img width="1232" height="982" alt="Image" src="https://github.com/user-attachments/assets/b89d2f46-944b-48ad-acf1-17e3de9677e7" />

**Comment by KonradLinden** [comment]
When I try to replicate the error I get a different one:

<img width="495" height="123" alt="Image" src="https://github.com/user-attachments/assets/948ab9e9-02d8-47bf-a5dc-08c3e7b45718" />

This might suggest that the issue is related to #77

**Comment by KonradLinden** [comment]
I noticed that the error message can differ when I rerun the query:

<img width="827" height="322" alt="Image" src="https://github.com/user-attachments/assets/a15b6c9a-54b2-41ac-8387-32e36092804e" />

**Comment by pfps** [comment]
That's probably due to different resources available at the time you run the query.

**Comment by pfps** [comment]
This appears to be due to a missing optimization in QLever.  I refactored the query in PR #100 at it appears to work better now.

**Comment by pfps** [comment]
Fixed

**Comment by egonw** [comment]
> Fixed

`@pfps, I still have the issue, at least for http://127.0.0.1:8100/location/Q1309:`

Sorry, plz ignore that. likely just the backend being down.
